#!/bin/bash
#step to install nodejs 12 version 

sudo apt update -y
cd ~
curl -sL https://deb.nodesource.com/setup_12.x -o /tmp/nodesource_setup.sh
sudo bash /tmp/nodesource_setup.sh
sudo apt install nodejs
